[build]
  command = "node src/render.js"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/feed.xml"
  to = "/.netlify/functions/feed"
  status = 200

[[redirects]]
  from = "/projects/:slug"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/projects/:slug/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/photos"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/photos/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/photos/:id/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/guestbook"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/guestbook/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/rss"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/rss/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
